# result in memory after merging default
ors:
  engine:
    profile_default:
      service:
        maximum_distance: 300000
        maximum_waypoints: 10
        maximum_snapping_radius: 300
    profiles:
      driving-car:
        service:
          maximum_distance: 400000
          maximum_waypoints: 10
          maximum_snapping_radius: 300
      driving-hgv:
        service:
          maximum_distance: 300000
          maximum_waypoints: 40
          maximum_snapping_radius: 200
      foot-walking:
        service:
          maximum_distance: 300000
          maximum_waypoints: 10
          maximum_snapping_radius: 400

