FROM registry.redhat.io/jboss-webserver-5/jws57-openjdk17-openshift-rhel8 as base

# Become root
USER root

# ARG REDHAT_ORG
# ARG REDHAT_ACTIVATION_KEY_NAME

# Allow container only redhat login. This process isn't the easiest and should stay commented out for now until we need it. For documentation purposes only.
# Taken from here: https://serverfault.com/questions/1106847/rhel-9-in-docker-container-on-macos-subscription-manager-is-disabled-when-runni
RUN sed -i 's/\(def in_container():\)/\1\n    return False/g' /usr/lib64/python*/*-packages/rhsm/config.py && \
    # Login to redhat. Register returns a non-zero exit code, even if it succeeds, so we need to catch it.
    # This is only needed if we have special repositories that are not available in the base image, e.g. for jws5* \
    #subscription-manager register --org=$REDHAT_ORG --activationkey=$REDHAT_ACTIVATION_KEY_NAME && \
    # Attach to the rhel8 repositories of the access key and unregister if it fails
    #subscription-manager attach || subscription-manager unregister && \
    # Update the system and unregister if it fails
    yum update -y && yum install -y git make && \
    # Clone fakeprovide and install it \
    git clone https://github.com/MichaelsJP/fakeprovide.git && cd fakeprovide && make install && \
    # Unregister from redhat in any case in the end to avoid too many registered systems
    #subscription-manager unregister \
    echo "Done"


from base as final

# Copy /usr/bin/fakeprovide from the base image
COPY --from=base /usr/bin/fakeprovide /usr/bin/fakeprovide

# Install rpm-build with yum as needed for fakeprovide and remove the yum cache
RUN yum install -y rpm-build && yum clean all && \
    # give user root the passwort "root"
    echo "root:root" | chpasswd

# Become the jboss user again
USER jboss
