name: 'Setup Java and Maven'
description: 'Set up JDK and Maven with dependency caching'

inputs:
  java_version:
    description: 'Java version to install'
    required: false
    default: '17'
outputs:
  cache-hit:
    description: 'Whether the Maven cache was hit'
runs:
  using: 'composite'
  steps:
    - name: Set up JDK ${{ inputs.java_version }}
      id: setup-java
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: ${{ inputs.java_version }}
        cache: 'maven'

    - name: Download maven dependencies
      if: steps.setup-java.outputs.cache-hit != 'true'
      shell: bash
      run: ./mvnw package -Dmaven.test.skip=true -B dependency:go-offline dependency:resolve-plugins dependency:resolve -q
