FROM docker.io/debian:bookworm-slim as builder
RUN apt-get update -y && \
    apt-get install -y openjdk-17-jdk-headless maven

ARG WORK_DIR=/home/ors/openrouteservice

WORKDIR $WORK_DIR

# TODO remove .m2
COPY .m2 /root/.m2
COPY ors-api ors-api
COPY ors-engine ors-engine
COPY ors-report-aggregation ors-report-aggregation
COPY pom.xml pom.xml

RUN mvn -B clean package -DskipTests -PbuildFatJar -DCI=true

FROM docker.io/debian:bookworm-slim as final

RUN apt-get update -y && \
    apt-get install -y openjdk-17-jdk-headless

ARG CONF_DIR_USER=/root/.config/openrouteservice
ARG CONF_DIR_ETC=/etc/openrouteservice
ARG WORK_DIR=/home/ors/openrouteservice

WORKDIR $WORK_DIR

COPY --from=builder /root/.m2 /root/.m2
COPY --from=builder $WORK_DIR/ors-api/target/ors.jar ors.jar
COPY ors-api/src/test/files ors-api/src/test/files

RUN mkdir graphs
RUN mkdir -p "$CONF_DIR_USER"
RUN mkdir -p "$CONF_DIR_ETC"

RUN chmod -R 770 .
RUN chmod -R 770 "$CONF_DIR_USER"
RUN chmod -R 770 "$CONF_DIR_ETC"

ENV JAVA_HOME=/usr/lib/jvm/java-17-openjdk-amd64

EXPOSE 8082

ENTRYPOINT [ "java", "-jar", "ors.jar" ]
