FROM docker.io/debian:bookworm-slim as builder

RUN apt-get update -y && \
    apt-get install -y openjdk-17-jdk-headless maven

ARG CONTAINER_CONF_DIR_USER=/root/.config/openrouteservice
ARG CONTAINER_CONF_DIR_ETC=/etc/openrouteservice
ARG CONTAINER_WORK_DIR=/home/ors/openrouteservice

WORKDIR $CONTAINER_WORK_DIR

COPY ors-api ors-api
COPY ors-engine ors-engine
COPY ors-report-aggregation ors-report-aggregation
COPY pom.xml pom.xml

RUN mvn clean package -DskipTests -PbuildFatJar -DCI=true

FROM docker.io/debian:bookworm-slim as final

RUN apt-get update -y && \
    apt-get install -y openjdk-17-jdk-headless

ARG CONTAINER_CONF_DIR_USER=/root/.config/openrouteservice
ARG CONTAINER_CONF_DIR_ETC=/etc/openrouteservice
ARG CONTAINER_WORK_DIR=/home/ors/openrouteservice

WORKDIR $CONTAINER_WORK_DIR

COPY --from=builder $CONTAINER_WORK_DIR/ors-api/target/ors.jar ors.jar
COPY ors-api/src/test/files ors-api/src/test/files

RUN mkdir graphs
RUN mkdir -p "$CONTAINER_CONF_DIR_USER"
RUN mkdir -p "$CONTAINER_CONF_DIR_ETC"

RUN chmod -R 770 .
RUN chmod -R 770 "$CONTAINER_CONF_DIR_USER"
RUN chmod -R 770 "$CONTAINER_CONF_DIR_ETC"

ENV JAVA_HOME=/usr/lib/jvm/java-17-openjdk-amd64

EXPOSE 8082

ENTRYPOINT [ "java", "-jar", "ors.jar" ]
