ors:
  engine:
    source_file:  ors-api/src/test/files/heidelberg.osm.gz
    profiles:
      public-transport:
        enabled: true
        profile: public-transport
        encoder_options:
          block_fords: false
        maximum_visited_nodes: 15000
        gtfs_file: ors-api/src/test/files/vrn_gtfs_cut.zip
