# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "**" ]

jobs:
  run_tests:
    name: Run unit and integration tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
        with:
          fetch-depth: 0
      - name: Setup build environment
        uses: ./.github/actions/setup-build-environment
        with:
          with_java: 'true'
          java_version: 25
          with_docker: 'false'
      - name: Cache SonarCloud packages
        uses: actions/cache@55cc8345863c7cc4c66a329aec7e433d2d1c52a9 # v6
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-sonar
      - name: run unit tests
        run: ./mvnw -B install -Papitests -T $(nproc) -DCI=true
      - name: Run the unit tests a second time with jacoco
        run: |
          # Ensure test stability across graph reloads.
          ./mvnw -B verify -Papitests -T $(nproc) jacoco:report
      - name: 'Prepare Sonar analysis'
        uses: evaristegalois11/sonar-fork-analysis@9d67a15f17407c3bf39bb09c39a9d5d3794eeecd # v1
        with:
          distribution: 'temurin'
          java-version: '25'
          github-token: ${{ secrets.GITHUB_TOKEN }}
          sonar-token: ${{ secrets.SONAR_TOKEN }}
          project-key: 'GIScience_openrouteservice'
