name: 'Sonar'
on:
  workflow_run:
    workflows: [ 'Java CI with Maven' ]
    types:
      - completed

permissions:
  contents: read

jobs:
  sonar:
    name: 'SonarCube Analysis'
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    permissions:
      actions: read # Required to download artifacts
    steps:
      - name: 'Sonar analysis'
        uses: evaristegalois11/sonar-fork-analysis@9d67a15f17407c3bf39bb09c39a9d5d3794eeecd # v1
        with:
          distribution: 'temurin'
          java-version: '25'
          github-token: ${{ secrets.GITHUB_TOKEN }}
          sonar-token: ${{ secrets.SONAR_TOKEN }}
          project-key: 'GIScience_openrouteservice'
